name: floor11 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Webcam streaming and sunset tweeting # 79 char long summary
description: |
  Webcam streaming and sunset tweeting

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: armhf
    run-on: armhf

apps:
  youtube-stream:
    command: bin/youtube-stream.sh

parts:
  ffmpeg:
    plugin: nil
    stage-snaps:
    - ffmpeg-integration-lgpl
    stage-packages:
        ### Dynamic-linking safe dependencies
        - libasound2
        - libass9
        - libbluray2
        - libbs2b0
        - libcaca0
        - libdrm2
        - libfontconfig1
        - libfribidi0
        - libgmp10
        - libgraphite2-3
        - libharfbuzz0b
        - libmp3lame0
        - try:
          - libnuma1
        - libogg0
        - libopencore-amrnb0
        - libopencore-amrwb0
        - libopus0
        - libslang2
        - libtheora0
        - libva-drm2
        - libva-x11-2
        - libva2
        - libvdpau1
        - libvo-amrwbenc0
        - libvorbis0a
        - libvorbisenc2
        - libvpx5
        - libx11-6
        - libxau6
        - libxcb-shape0
        - libxcb-shm0
        - libxcb-xfixes0
        - libxdmcp6
        - libxext6
        - libxfixes3
        - libgl1
        - libglu1-mesa
        - freeglut3
  youtube-stream:
    plugin: dump
    source: .
    organize:
      youtube-stream.sh: bin/
    stage-packages:
      - v4l-utils
